stages:
  - test
  - release

variables:
  BUILD_COMMIT: $CI_COMMIT_SHORT_SHA
  BUILD_BRANCH: $CI_COMMIT_REF_NAME
  BUILD_BRANCH_SAFE: $CI_COMMIT_REF_SLUG
  BUILD_TAG: $CI_COMMIT_TAG
  BUILD_NUMBER: $CI_PIPELINE_ID
  GITHUB_OWNER: mysteriumnetwork
  GITHUB_REPO: payments-smart-contracts

  GO_PACKAGE: github.com/mysteriumnetwork/payments-smart-contracts
  GIT_CLONE_PATH: /home/gitlab-runner/go/src/$GO_PACKAGE
  GOFLAGS: "-count=1" # Supersedes GOCACHE=off, see: https://github.com/golang/go/issues/29378#issuecomment-449383809

after_script:
  # docker based jobs leave files owned by root
  - sudo chown -R gitlab-runner:gitlab-runner $GOPATH

e2e:
  stage: test
  tags: [go]
  script: go run mage.go -v e2e

artifacts:
  only:
    - tags
  stage: release
  tags: [go]
  script: go run mage.go -v release


